---
kind: pipeline
type: docker
name: default

steps:
- name: hello
  image: busybox
  commands:
  - echo hello world
  - sleep 1
  - echo hello world 2
  - sleep 1
  - echo hello world 3
 
trigger:
  branch:
  - main
